### ISSUE TITLE
Runner Status: Create/improve demo

### ISSUE THREAD

**Issue by savostin** [TotalPerformanceData/demos#1]
For the TPD site. This will create a user friendly demonstration of the runner status system for internal use and/or external testing

**Comment by KendallTPD** [comment]
We will collate work here following testing on https://github.com/TotalPerformanceData/zone_streaming/issues/93

**Comment by savostin** [comment]
Base on [New Runner Status API endpoint](https://github.com/TotalPerformanceData/zone_streaming/issues/104)

**Comment by savostin** [comment]
v 2024.03.12: https://stg.tpd.zone/demos/runner_status/

**Comment by savostin** [comment]
v.2024.03.13

1. Cosmetic improvements
2. Non-flat races
3. Playing speed

**Comment by savostin** [comment]
- [x] Add live races (connect to live Runner Status API)

**Comment by savostin** [comment]
Now live https://www.tpd.zone/data-demos/samples/runner_status/
